import Head from "next/head";
import Header from "@/shared/components/layout/header";
import Filter from "@/shared/components/filter";
import ProductShowcase from "@/shared/components/product-showcase";

export default function Home() {
  return (
    <>
      <section id="header">
        <Head>
          <title>Catalogue Web Apps | Yusril Firza</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <Header />
      </section>
      <Filter />
      <section id="brand-tagline">
        <h1>All-In-One Shop</h1>
        <span>Shop with us. Saving more cash.</span>
      </section>
      <section id="product-showcase">
        <ProductShowcase />
      </section>
      <section id="footer">
        © by Yusril Firza
      </section>
    </>
  );
}
